apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-customer-flask-app
  labels:
    name: {{ .Release.Name }}-customer-flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-customer-flask-app
  template:
    metadata:
      name: {{ .Release.Name }}-customer-flask-app
      labels:
        name: {{ .Release.Name }}-customer-flask-app
    spec:
      containers:
        - name: customer-flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
