apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-customer-service
spec:
  selector:
    name: {{ .Release.Name }}-customer-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
